cache:
  timeout: 660
  pip: true
  custom_install: true
  directories:
    - build/llvm
    - third_party/llvm

matrix:
    include:
        - os: linux
          dist: trusty
          language: generic
          sudo: required
        - os: osx
          language: generic
          sudo: required

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update          ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qqy libxml2-dev git cmake libprotoc-dev libprotobuf-dev libprotobuf-dev protobuf-compiler python2.7 python-pip llvm-3.8 clang-3.8 realpath gcc-multilib; fi
 - sudo -H pip install 'protobuf==2.6.1'
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                        ; fi
install: true
script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bootstrap.sh                     ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then CC=clang CXX=clang++ ./bootstrap.sh; fi
 - python tests/integration_test.py
notifications:
  slack:
    secure: g1Nm7C7TYKg4RjDJ5cwuEcgKXfOAmVOu51adTPLBLGzZcCbCrkwQgI39ZycsalaACSnC8iNvqSCbRfZIA5mkDZ7VADaiZgLoWjq3RQzJmWgwGhhtyRkbtiicBnowTL5hIEiMOv6RnKlbB7M2OwzRiS07+FQXrK24hz+qm6zPptw=
